import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader } from "@/components/ui/card";
import {
  Accordion,
  AccordionItem,
  AccordionTrigger,
  AccordionContent,
} from "@/components/ui/accordion";
import { motion, useTransform, useScroll } from "framer-motion";
import Lottie from "lottie-react";
import dreamAnimation from "../assets/lotties/cloud-bg.json";
import {
  Sparkles,
  BrainCircuit,
  Image,
  BarChartBig,
  Quote,
  BrainCog,
  Eye,
  ImagePlus,
  Facebook,
  Twitter,
  Instagram,
  Notebook,
  Bot,
  Radar,
} from "lucide-react";

import ParticlesBackground from "../components/ParticleBackground";
import { useState } from "react";
import OnboardingPage from "../components/onboarding/OnBoardingPage";

const features = [
  {
    icon: <BrainCircuit className="w-8 h-8 text-indigo-500" />,
    title: "AI-Powered Interpretation",
    desc: "Deep dream decoding using natural language understanding and symbolic clustering.",
  },
  {
    icon: <BarChartBig className="w-8 h-8 text-pink-500" />,
    title: "Emotional & Symbolic Analytics",
    desc: "Visualize your dream's emotional tone, objects, and deeper patterns.",
  },
  {
    icon: <Image className="w-8 h-8 text-purple-500" />,
    title: "Generate Dream Art",
    desc: "Transform your dreams into stunning visuals using AI image generation.",
  },
  {
    icon: <Sparkles className="w-8 h-8 text-yellow-500" />,
    title: "Personal Clusters & Journals",
    desc: "Group dreams by themes or characters, track your subconscious over time.",
  },
];

const testimonials = [
  {
    name: "Aryan S.",
    feedback:
      "This platform helped me understand a recurring nightmare. The AI explanation gave me clarity and peace!",
  },
  {
    name: "Priya N.",
    feedback:
      "I love how it turns dreams into visual art. It's like my subconscious finally has a canvas.",
  },
  {
    name: "Kunal M.",
    feedback:
      "I track my dreams weekly and notice patterns I never saw before. Total game changer.",
  },
];

const benefits = [
  {
    title: "Dream Analysis",
    description:
      "Understand the hidden meanings behind your dreams using advanced AI interpretation.",
    icon: Sparkles,
  },
  {
    title: "Emotional Mapping",
    description:
      "Track the emotional tone and intensity of your dreams to uncover patterns.",
    icon: BrainCog,
  },
  {
    title: "Keyword Extraction",
    description:
      "Visualize key symbols and themes from your subconscious through word clouds and graphs.",
    icon: Eye,
  },
  {
    title: "Visual Dreamscapes",
    description:
      "See your dreams transformed into surreal art generated by AI.",
    icon: ImagePlus,
  },
];

export default function DreamLandingPage() {
  const [showWelcomeOverlay, setShowWelcomeOverlay] = useState(false);
  const { scrollY } = useScroll();
  // parallax transforms
  const y1 = useTransform(scrollY, [0, 500], [0, 100]);
  const y2 = useTransform(scrollY, [0, 500], [0, -50]);

  return (
    <div className="relative overflow-hidden">
      {/* Animated Gradient Layer */}
      <motion.div
        style={{ y: y2 }}
        className="absolute inset-0 bg-gradient-to-br from-indigo-900 via-purple-800 to-black animate-gradient bg-200%"
      />

      {/* Particle Starfield */}
      {/* {engineReady && <Particles id="tsparticles" options={particleOptions} />} */}
      <ParticlesBackground />

      {/* Lottie Background Subtle Clouds */}
      <motion.div style={{ y: y1 }} className="absolute inset-0 opacity-30">
        <Lottie animationData={dreamAnimation} loop autoplay />
      </motion.div>

      {/* Content Wrapper */}
      <div className="relative z-10 text-white">
        {/* Hero */}
        <section className="min-h-screen flex flex-col items-center justify-center text-center px-6">
          <motion.h1
            initial={{ opacity: 0, y: 40 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 1 }}
            className="text-5xl md:text-6xl font-bold leading-tight"
          >
            Decode Your Dreams, Discover Yourself
          </motion.h1>
          <motion.p
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            transition={{ delay: 0.5 }}
            className="mt-4 text-lg max-w-2xl"
          >
            Dive into your subconscious with AI-powered interpretations, visual
            insights, and a vibrant community.
          </motion.p>
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.8 }}
            className="mt-8 flex items-center gap-4"
          >
            {/* Primary CTA */}
            <Button
              size="lg"
              className="px-8 py-4 bg-white text-black rounded-xl shadow-lg hover:bg-gray-200 transition"
              onClick={() => setShowWelcomeOverlay(true)}
            >
              Start Exploring
            </Button>

            {/* Secondary CTA */}
            <a href={"/login"}>
              <Button
                size="lg"
                variant="ghost"
                className="px-8 py-4 text-white/80 hover:text-white hover:bg-white/10 rounded-xl transition"
              >
                Log in
              </Button>
            </a>
          </motion.div>
        </section>

        {showWelcomeOverlay && (
          // <WelcomeOverlay setShowWelcomeOverlay={setShowWelcomeOverlay} />
          <OnboardingPage setShowWelcomeOverlay={setShowWelcomeOverlay} />
        )}

        {/* Benefits */}
        <section className="py-24 px-6 dark:bg-zinc-950 text-center">
          <motion.h2
            initial={{ opacity: 0, y: 30 }}
            whileInView={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.8 }}
            className="text-4xl sm:text-5xl font-bold mb-6"
          >
            What You Can Do
          </motion.h2>
          <motion.p
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.2, duration: 0.8 }}
            className="text-muted-foreground mb-12 max-w-xl mx-auto"
          >
            Our platform lets you explore, visualize, and understand your dreams
            like never before.
          </motion.p>

          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6 max-w-6xl mx-auto">
            {benefits.map((feature, index) => (
              <motion.div
                key={index}
                initial={{ opacity: 0, y: 30 }}
                whileInView={{ opacity: 1, y: 0 }}
                transition={{ delay: index * 0.1 }}
              >
                <Card className="p-6 border-border bg-card shadow-md hover:shadow-xl transition duration-300 rounded-2xl">
                  <CardHeader className="flex items-center justify-center mb-4">
                    <feature.icon className="h-10 w-10 text-indigo-600" />
                  </CardHeader>
                  <CardContent>
                    <h3 className="text-xl font-semibold mb-2">
                      {feature.title}
                    </h3>
                    <p className="text-sm text-muted-foreground">
                      {feature.description}
                    </p>
                  </CardContent>
                </Card>
              </motion.div>
            ))}
          </div>
        </section>

        {/* Tabs + Search as optional navigation*/}
        {/* <section className="py-12 px-6">
          <Tabs defaultValue="all" className="max-w-3xl mx-auto">
            <TabsList className="grid grid-cols-4">
              <TabsTrigger value="all">All Dreams</TabsTrigger>
              <TabsTrigger value="recurring">Recurring</TabsTrigger>
              <TabsTrigger value="peaceful">Peaceful</TabsTrigger>
              <TabsTrigger value="nightmare">Nightmares</TabsTrigger>
            </TabsList>
          </Tabs>
        </section> */}

        {/* How It Works */}
        <section className="py-24 px-6 text-center">
          <h2 className="text-4xl font-bold mb-10">How It Works</h2>
          <div className="max-w-4xl mx-auto grid sm:grid-cols-3 gap-8">
            {[
              {
                icon: Notebook,
                title: "Log Your Dream",
                desc: "Write your dream details and emotions without limits.",
              },
              {
                icon: Bot,
                title: "AI Interprets",
                desc: "Advanced NLP decodes symbolism, mood, and meaning.",
              },
              {
                icon: Radar,
                title: "Visualize Insights",
                desc: "See charts, word clouds, and AI-generated art.",
              },
            ].map((s, i) => (
              <motion.div
                key={i}
                initial={{ opacity: 0, y: 30 }}
                whileInView={{ opacity: 1, y: 0 }}
                transition={{ delay: i * 0.2 }}
              >
                <Card className="bg-white/10 border border-white/20 backdrop-blur-lg rounded-2xl p-6">
                  <CardHeader className="flex justify-center mb-4">
                    <s.icon className="w-8 h-8 text-white" />
                  </CardHeader>
                  <CardContent>
                    <h3 className="text-xl font-semibold mb-2">{s.title}</h3>
                    <p className="text-sm text-white/80">{s.desc}</p>
                  </CardContent>
                </Card>
              </motion.div>
            ))}
          </div>
        </section>

        {/* Features */}
        <section className="py-24 px-6 bg-black/50">
          <h2 className="text-4xl font-bold text-center mb-12">
            Features & Benefits
          </h2>
          <div className="max-w-6xl mx-auto grid sm:grid-cols-2 lg:grid-cols-4 gap-8">
            {features.map((f, idx) => (
              <motion.div
                key={idx}
                initial={{ opacity: 0, scale: 0.95 }}
                whileInView={{ opacity: 1, scale: 1 }}
                transition={{ delay: idx * 0.1 }}
              >
                <Card className="bg-white/10 border border-white/20 backdrop-blur-lg rounded-2xl p-6 hover:shadow-xl transition">
                  <CardHeader className="flex justify-center mb-4">
                    {f.icon}
                  </CardHeader>
                  <CardContent>
                    <h4 className="text-lg font-semibold text-white mb-2">
                      {f.title}
                    </h4>
                    <p className="text-sm text-white/80">{f.desc}</p>
                  </CardContent>
                </Card>
              </motion.div>
            ))}
          </div>
        </section>

        {/* Testimonials */}
        <section className="py-24 px-6 text-center">
          <h2 className="text-4xl font-bold mb-12">What Dreamers Say</h2>
          <div className="max-w-5xl mx-auto grid md:grid-cols-3 gap-8">
            {testimonials.map((t, i) => (
              <motion.div
                key={i}
                initial={{ opacity: 0, y: 30 }}
                whileInView={{ opacity: 1, y: 0 }}
                transition={{ delay: i * 0.2 }}
              >
                <Card className="bg-white/10 border border-white/20 backdrop-blur-lg rounded-2xl p-6">
                  <CardContent>
                    <Quote className="w-6 h-6 text-white mb-4" />
                    <p className="italic text-white/80 mb-4">“{t.feedback}”</p>
                    <p className="font-semibold text-white">- {t.name}</p>
                  </CardContent>
                </Card>
              </motion.div>
            ))}
          </div>
        </section>

        {/* FAQ & Safety */}
        <section className="py-24 px-6 bg-black/50">
          <h2 className="text-4xl font-bold text-center mb-10">
            FAQs & Privacy
          </h2>
          <div className="max-w-3xl mx-auto">
            <Accordion type="single" collapsible className="space-y-4">
              {[
                {
                  q: "How are dreams interpreted?",
                  a: "We use AI trained on symbolic language and emotion models to decode your dreams privately.",
                },
                {
                  q: "Is my data secure?",
                  a: "All entries are encrypted client‑side and never shared without your permission.",
                },
                {
                  q: "Can I delete my dreams?",
                  a: "Yes — you control your dream archive fully, with one click deletion.",
                },
                {
                  q: "Who sees my dream art?",
                  a: "Your generated art and insights remain private unless you choose to share them.",
                },
              ].map((item, i) => (
                <AccordionItem key={i} value={`faq${i}`}>
                  <AccordionTrigger className="text-white">
                    ❓ {item.q}
                  </AccordionTrigger>
                  <AccordionContent className="text-white/80">
                    {item.a}
                  </AccordionContent>
                </AccordionItem>
              ))}
            </Accordion>
          </div>
        </section>

        {/* Final CTA */}
        <section className="py-24 px-6 text-center">
          <motion.h2
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6 }}
            className="text-4xl font-bold mb-4"
          >
            Ready to Explore Your Inner World?
          </motion.h2>
          <Button
            size="lg"
            className="px-8 py-4 bg-indigo-600 hover:bg-indigo-500 transition text-white rounded-xl"
            onClick={() => setShowWelcomeOverlay(true)}
          >
            Begin Your Journey
          </Button>
        </section>

        {/* Footer */}
        <footer className="py-12 px-6 bg-black text-white text-center space-y-4">
          {" "}
          <div className="flex justify-center gap-6">
            <a href="#">
              <Facebook className="w-6 h-6 hover:text-indigo-400" />
            </a>
            <a href="#">
              <Twitter className="w-6 h-6 hover:text-cyan-400" />
            </a>
            <a href="#">
              <Instagram className="w-6 h-6 hover:text-pink-400" />
            </a>
          </div>
          <p className="text-sm">
            © {new Date().getFullYear()} DreamScope. All rights reserved.
          </p>
        </footer>
      </div>
    </div>
  );
}
