const renderBaseHTML = require("../base/baseHTML");
const { safeJSONStringify } = require("../base/seoUtils");

const PUBLIC_ORIGIN = process.env.PUBLIC_ORIGIN || "http://localhost:8080";

module.exports = function renderDisclaimerHTML() {
  const bodyHTML = `
  <style>
    body {
      margin: 0;
      background: radial-gradient(circle at top, #1e1b4b, #020617);
      color: #e5e7eb;
      font-family: Inter, system-ui, sans-serif;
    }

    .seo-container {
      max-width: 880px;
      margin: 0 auto;
      padding: 120px 24px 160px;
      text-align: center;
    }

    h1 {
      font-size: 3rem;
      font-weight: 700;
      margin-bottom: 32px;
      color: #ffffff;
    }

    p {
      font-size: 1.1rem;
      line-height: 1.9;
      color: #cbd5f5;
      margin-bottom: 22px;
    }

    .highlight {
      margin: 64px auto;
      padding: 36px;
      border-radius: 24px;
      background: rgba(255,255,255,0.06);
      border: 1px solid rgba(255,255,255,0.1);
      max-width: 700px;
    }

    .footer-links {
  margin-top: 48px;
  text-align: center;
  font-size: 0.85rem;
  color: rgba(203, 213, 225, 0.6); /* slate-300 / muted */
  display: flex;
  justify-content: center;
  gap: 10px;
  flex-wrap: wrap;
}

.footer-links a {
  color: rgba(199, 210, 254, 0.75); /* indigo-200 */
  text-decoration: none;
  transition: color 0.2s ease, opacity 0.2s ease;
}

.footer-links a:hover {
  color: #ffffff;
  opacity: 0.9;
}

.footer-links span {
  opacity: 0.4;
  user-select: none;
}


  </style>

  <main class="seo-container">
    <h1>Disclaimer</h1>

    <p>
      SomniaMind provides AI-generated dream interpretations intended
      solely for reflection and personal insight.
    </p>

    <div class="highlight">
      <p>
        SomniaMind does <strong>not</strong> provide medical, psychological,
        or professional advice.
      </p>
    </div>

    <p>
      Interpretations are not factual statements or predictions.
      They are generated by artificial intelligence and may not
      reflect objective truth.
    </p>

    <p>
      If you experience distressing dreams, anxiety, or mental health concerns,
      please seek guidance from a qualified professional.
    </p>

    <p>
      By using SomniaMind, you acknowledge that all interpretations are
      exploratory and that you are responsible for how you apply them.
    </p>
   <div class="footer-links">
  <a href="/privacy">Privacy Policy</a>
  <span>·</span>
  <a href="/terms">Terms of Use</a>
  <span>·</span>
  <a href="/disclaimer">Disclaimer</a>
</div>

  </main>
  `;

  return renderBaseHTML({
    title: "Disclaimer – SomniaMind",
    description:
      "SomniaMind provides AI-generated dream interpretations for reflection only. Not medical or psychological advice.",
    canonical: `${PUBLIC_ORIGIN}/disclaimer`,
    ogTitle: "Disclaimer – SomniaMind",
    ogDescription:
      "AI dream interpretations are reflective tools, not professional advice.",
    ogImage: `${PUBLIC_ORIGIN}/og-image.png`,
    ogUrl: `${PUBLIC_ORIGIN}/disclaimer`,
    bodyHTML,
  });
};
