const renderBaseHTML = require("../base/baseHTML");
const { safeJSONStringify } = require("../base/seoUtils");

const PUBLIC_ORIGIN = process.env.PUBLIC_ORIGIN || "http://localhost:8080";

module.exports = function renderTermsHTML() {
  const bodyHTML = `
  <style>
    body {
      margin: 0;
      background: radial-gradient(circle at top, #1e1b4b, #020617);
      color: #e5e7eb;
      font-family: Inter, system-ui, sans-serif;
    }

    .seo-container {
      max-width: 900px;
      margin: 0 auto;
      padding: 120px 24px 160px;
    }

    h1 {
      font-size: 3rem;
      font-weight: 700;
      margin-bottom: 24px;
      color: #ffffff;
      text-align: center;
    }

    .intro {
      font-size: 1.2rem;
      color: #c7d2fe;
      text-align: center;
      margin-bottom: 80px;
    }

    h2 {
      font-size: 1.8rem;
      margin-top: 72px;
      margin-bottom: 16px;
      color: #f8fafc;
    }

    p {
      font-size: 1.05rem;
      line-height: 1.85;
      color: #cbd5f5;
      margin-bottom: 18px;
    }

    .footer-links {
  margin-top: 48px;
  text-align: center;
  font-size: 0.85rem;
  color: rgba(203, 213, 225, 0.6); /* slate-300 / muted */
  display: flex;
  justify-content: center;
  gap: 10px;
  flex-wrap: wrap;
}

.footer-links a {
  color: rgba(199, 210, 254, 0.75); /* indigo-200 */
  text-decoration: none;
  transition: color 0.2s ease, opacity 0.2s ease;
}

.footer-links a:hover {
  color: #ffffff;
  opacity: 0.9;
}

.footer-links span {
  opacity: 0.4;
  user-select: none;
}

  </style>

  <main class="seo-container">
    <h1>Terms of Use</h1>

    <p class="intro">
      These terms govern your use of SomniaMind. By using the platform,
      you agree to the conditions outlined below.
    </p>

    <h2>Eligibility</h2>
    <p>
      You must be at least 13 years old to use SomniaMind. By using the service,
      you confirm that you meet this requirement.
    </p>

    <h2>Your Content</h2>
    <p>
      You retain full ownership of all dreams and content you submit.
      SomniaMind does not claim ownership over your personal entries.
    </p>

    <h2>Acceptable Use</h2>
    <p>
      You agree not to misuse the platform, attempt unauthorized access,
      or use the service for unlawful purposes.
    </p>

    <h2>Service Availability</h2>
    <p>
      We may modify or discontinue features at any time. We are not liable
      for interruptions or data loss.
    </p>

    <h2>Limitation of Liability</h2>
    <p>
      SomniaMind is provided “as is.” We are not responsible for decisions
      made based on interpretations generated by the platform.
    </p>
    <div class="footer-links">
  <a href="/privacy">Privacy Policy</a>
  <span>·</span>
  <a href="/terms">Terms of Use</a>
  <span>·</span>
  <a href="/disclaimer">Disclaimer</a>
</div>

  </main>
  `;

  return renderBaseHTML({
    title: "Terms of Use – SomniaMind",
    description:
      "Read the terms governing your use of SomniaMind’s AI dream interpretation platform.",
    canonical: `${PUBLIC_ORIGIN}/terms`,
    ogTitle: "Terms of Use – SomniaMind",
    ogDescription: "Understand the terms and conditions for using SomniaMind.",
    ogImage: `${PUBLIC_ORIGIN}/og-image.png`,
    ogUrl: `${PUBLIC_ORIGIN}/terms`,
    bodyHTML,
  });
};
